version: "3"

output: prefixed

env:
  CGO_ENABLED: 0
  IMAGE_DEV: ko.local/beacon
  IMAGE_PROD: ghcr.io/mizuchilabs/beacon
  LD_FLAGS: -s -w -X main.version={{.VERSION}}

tasks:
  seed:
    desc: Generate seed data
    cmds:
      - go run ./examples/main.go

  dev:
    desc: Run backend and frontend concurrently
    deps: [backend, frontend]

  backend:
    desc: Run backend
    cmds:
      - go run .

  frontend:
    desc: Run frontend
    dir: web
    cmds:
      - pnpm run dev

  # 󰚰 Update deps
  update:
    desc: Update dependencies
    cmds:
      - go get -u ./...
      - cd web && pnpm update --latest

  #  Generate code
  gen:
    desc: Generate sqlc
    cmds:
      - sqlc generate

  # 󰉠  Lint / static checks
  lint:
    desc: Run go vet & lint
    cmds:
      - go mod tidy
      - go fmt ./...
      - go vet ./...
      - go test -cover ./...

  build:
    desc: Build binary
    cmds:
      - cd web; pnpm install; pnpm build
      - go build -ldflags "{{.LD_FLAGS}}" -o beacon

  snapshot:
    desc: Test snapshot
    cmds:
      - goreleaser --snapshot --clean --skip=validate

  # 󰡨  Build container with ko
  docker:dev:
    desc: Build OCI image with ko
    deps: [build:web]
    dir: cmd
    cmds:
      - KO_DOCKER_REPO=$IMAGE_DEV ko build --bare .
      - grype $IMAGE_DEV

  docker:prod:
    desc: Build OCI image with ko
    deps: [build:web]
    dir: cmd
    cmds:
      - KO_DOCKER_REPO=$IMAGE_PROD ko build --bare .
      - grype $IMAGE_PROD
