// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checks.sql

package db

import (
	"context"
)

const createCheck = `-- name: CreateCheck :one
INSERT INTO
  checks (
    monitor_id,
    status_code,
    response_time,
    error,
    is_up
  )
VALUES
  (?, ?, ?, ?, ?) RETURNING id, monitor_id, status_code, response_time, error, is_up, checked_at
`

type CreateCheckParams struct {
	MonitorID    int64   `json:"monitorId"`
	StatusCode   *int64  `json:"statusCode"`
	ResponseTime *int64  `json:"responseTime"`
	Error        *string `json:"error"`
	IsUp         bool    `json:"isUp"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg *CreateCheckParams) (*Check, error) {
	row := q.queryRow(ctx, q.createCheckStmt, createCheck,
		arg.MonitorID,
		arg.StatusCode,
		arg.ResponseTime,
		arg.Error,
		arg.IsUp,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StatusCode,
		&i.ResponseTime,
		&i.Error,
		&i.IsUp,
		&i.CheckedAt,
	)
	return &i, err
}

const deleteCheck = `-- name: DeleteCheck :exec
DELETE FROM checks
WHERE
  id = ?
`

func (q *Queries) DeleteCheck(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteCheckStmt, deleteCheck, id)
	return err
}

const getCheck = `-- name: GetCheck :one
SELECT
  id, monitor_id, status_code, response_time, error, is_up, checked_at
FROM
  checks
WHERE
  id = ?
`

func (q *Queries) GetCheck(ctx context.Context, id int64) (*Check, error) {
	row := q.queryRow(ctx, q.getCheckStmt, getCheck, id)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StatusCode,
		&i.ResponseTime,
		&i.Error,
		&i.IsUp,
		&i.CheckedAt,
	)
	return &i, err
}

const getChecks = `-- name: GetChecks :many
SELECT
  id, monitor_id, status_code, response_time, error, is_up, checked_at
FROM
  checks
WHERE
  monitor_id = ?
`

func (q *Queries) GetChecks(ctx context.Context, monitorID int64) ([]*Check, error) {
	rows, err := q.query(ctx, q.getChecksStmt, getChecks, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Check
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StatusCode,
			&i.ResponseTime,
			&i.Error,
			&i.IsUp,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheck = `-- name: UpdateCheck :one
UPDATE checks
SET
  status_code = COALESCE(?, status_code),
  response_time = COALESCE(?, response_time),
  error = COALESCE(?, error),
  is_up = COALESCE(?, is_up)
WHERE
  id = ? RETURNING id, monitor_id, status_code, response_time, error, is_up, checked_at
`

type UpdateCheckParams struct {
	StatusCode   *int64  `json:"statusCode"`
	ResponseTime *int64  `json:"responseTime"`
	Error        *string `json:"error"`
	IsUp         bool    `json:"isUp"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateCheck(ctx context.Context, arg *UpdateCheckParams) (*Check, error) {
	row := q.queryRow(ctx, q.updateCheckStmt, updateCheck,
		arg.StatusCode,
		arg.ResponseTime,
		arg.Error,
		arg.IsUp,
		arg.ID,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StatusCode,
		&i.ResponseTime,
		&i.Error,
		&i.IsUp,
		&i.CheckedAt,
	)
	return &i, err
}
