// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package db

import (
	"context"
)

const cleanupChecks = `-- name: CleanupChecks :exec
DELETE FROM checks
WHERE
  checked_at < ?1
`

func (q *Queries) CleanupChecks(ctx context.Context, cutoff int64) error {
	_, err := q.db.ExecContext(ctx, cleanupChecks, cutoff)
	return err
}

const getCheckResponseTimes = `-- name: GetCheckResponseTimes :many
SELECT
  monitor_id,
  response_time
FROM
  checks
WHERE
  checked_at >= ?1
  AND is_up
ORDER BY
  monitor_id,
  response_time
`

type GetCheckResponseTimesRow struct {
	MonitorID    int64 `json:"monitorId"`
	ResponseTime int64 `json:"responseTime"`
}

func (q *Queries) GetCheckResponseTimes(ctx context.Context, fromTs int64) ([]*GetCheckResponseTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCheckResponseTimes, fromTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCheckResponseTimesRow
	for rows.Next() {
		var i GetCheckResponseTimesRow
		if err := rows.Scan(&i.MonitorID, &i.ResponseTime); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckWindow = `-- name: GetCheckWindow :many
SELECT
  monitor_id,
  checked_at - (checked_at % ?1) AS ts,
  COUNT(*) AS total,
  CAST(
    SUM(
      CASE
        WHEN is_up
        AND response_time <= ?2 THEN 1
        ELSE 0
      END
    ) AS INTEGER
  ) AS up,
  CAST(
    SUM(
      CASE
        WHEN is_up
        AND response_time > ?2 THEN 1
        ELSE 0
      END
    ) AS INTEGER
  ) AS degraded,
  CAST(
    SUM(
      CASE
        WHEN NOT is_up THEN 1
        ELSE 0
      END
    ) AS INTEGER
  ) AS down,
  CAST(SUM(response_time) AS INTEGER) AS sum_ms
FROM
  checks
WHERE
  checked_at >= ?3
GROUP BY
  monitor_id,
  ts
ORDER BY
  monitor_id,
  ts
`

type GetCheckWindowParams struct {
	Step              int64 `json:"step"`
	DegradedThreshold int64 `json:"degradedThreshold"`
	FromTs            int64 `json:"fromTs"`
}

type GetCheckWindowRow struct {
	MonitorID int64 `json:"monitorId"`
	Ts        int64 `json:"ts"`
	Total     int64 `json:"total"`
	Up        int64 `json:"up"`
	Degraded  int64 `json:"degraded"`
	Down      int64 `json:"down"`
	SumMs     int64 `json:"sumMs"`
}

func (q *Queries) GetCheckWindow(ctx context.Context, arg *GetCheckWindowParams) ([]*GetCheckWindowRow, error) {
	rows, err := q.db.QueryContext(ctx, getCheckWindow, arg.Step, arg.DegradedThreshold, arg.FromTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCheckWindowRow
	for rows.Next() {
		var i GetCheckWindowRow
		if err := rows.Scan(
			&i.MonitorID,
			&i.Ts,
			&i.Total,
			&i.Up,
			&i.Degraded,
			&i.Down,
			&i.SumMs,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestChecks = `-- name: GetLatestChecks :many
SELECT
  c.monitor_id,
  c.status_code,
  c.response_time,
  c.is_up,
  c.checked_at
FROM
  monitors m
  JOIN checks c ON c.monitor_id = m.id
WHERE
  c.checked_at = (
    SELECT
      MAX(c2.checked_at)
    FROM
      checks c2
    WHERE
      c2.monitor_id = m.id
  )
`

type GetLatestChecksRow struct {
	MonitorID    int64 `json:"monitorId"`
	StatusCode   int64 `json:"statusCode"`
	ResponseTime int64 `json:"responseTime"`
	IsUp         bool  `json:"isUp"`
	CheckedAt    int64 `json:"checkedAt"`
}

func (q *Queries) GetLatestChecks(ctx context.Context) ([]*GetLatestChecksRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetLatestChecksRow
	for rows.Next() {
		var i GetLatestChecksRow
		if err := rows.Scan(
			&i.MonitorID,
			&i.StatusCode,
			&i.ResponseTime,
			&i.IsUp,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCheck = `-- name: UpsertCheck :exec
INSERT INTO
  checks (monitor_id, status_code, response_time, error, is_up, checked_at)
VALUES
  (?, ?, ?, ?, ?, ?)
ON CONFLICT (monitor_id, checked_at) DO UPDATE
SET
  status_code = excluded.status_code,
  response_time = excluded.response_time,
  error = excluded.error,
  is_up = excluded.is_up
`

type UpsertCheckParams struct {
	MonitorID    int64   `json:"monitorId"`
	StatusCode   int64   `json:"statusCode"`
	ResponseTime int64   `json:"responseTime"`
	Error        *string `json:"error"`
	IsUp         bool    `json:"isUp"`
	CheckedAt    int64   `json:"checkedAt"`
}

func (q *Queries) UpsertCheck(ctx context.Context, arg *UpsertCheckParams) error {
	_, err := q.db.ExecContext(ctx, upsertCheck,
		arg.MonitorID,
		arg.StatusCode,
		arg.ResponseTime,
		arg.Error,
		arg.IsUp,
		arg.CheckedAt,
	)
	return err
}
