// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checks.sql

package db

import (
	"context"
)

const cleanupChecks = `-- name: CleanupChecks :exec
DELETE FROM checks
WHERE
  checked_at < datetime ('now', '-' || ?1 || ' days')
`

func (q *Queries) CleanupChecks(ctx context.Context, days *string) error {
	_, err := q.exec(ctx, q.cleanupChecksStmt, cleanupChecks, days)
	return err
}

const createCheck = `-- name: CreateCheck :one
INSERT INTO
  checks (
    monitor_id,
    status_code,
    response_time,
    error,
    is_up
  )
VALUES
  (?, ?, ?, ?, ?) RETURNING id, monitor_id, status_code, response_time, error, is_up, checked_at
`

type CreateCheckParams struct {
	MonitorID    int64   `json:"monitorId"`
	StatusCode   *int64  `json:"statusCode"`
	ResponseTime *int64  `json:"responseTime"`
	Error        *string `json:"error"`
	IsUp         bool    `json:"isUp"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg *CreateCheckParams) (*Check, error) {
	row := q.queryRow(ctx, q.createCheckStmt, createCheck,
		arg.MonitorID,
		arg.StatusCode,
		arg.ResponseTime,
		arg.Error,
		arg.IsUp,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StatusCode,
		&i.ResponseTime,
		&i.Error,
		&i.IsUp,
		&i.CheckedAt,
	)
	return &i, err
}

const getChecks = `-- name: GetChecks :many
SELECT
  id, monitor_id, status_code, response_time, error, is_up, checked_at
FROM
  checks
WHERE
  monitor_id = ?
  AND checked_at >= datetime ('now', '-' || ?2 || ' seconds')
ORDER BY
  checked_at DESC
`

type GetChecksParams struct {
	MonitorID int64   `json:"monitorId"`
	Seconds   *string `json:"seconds"`
}

func (q *Queries) GetChecks(ctx context.Context, arg *GetChecksParams) ([]*Check, error) {
	rows, err := q.query(ctx, q.getChecksStmt, getChecks, arg.MonitorID, arg.Seconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Check
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StatusCode,
			&i.ResponseTime,
			&i.Error,
			&i.IsUp,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
