// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.cleanupChecksStmt, err = db.PrepareContext(ctx, cleanupChecks); err != nil {
		return nil, fmt.Errorf("error preparing query CleanupChecks: %w", err)
	}
	if q.createCheckStmt, err = db.PrepareContext(ctx, createCheck); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCheck: %w", err)
	}
	if q.createMonitorStmt, err = db.PrepareContext(ctx, createMonitor); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMonitor: %w", err)
	}
	if q.createPushSubscriptionStmt, err = db.PrepareContext(ctx, createPushSubscription); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePushSubscription: %w", err)
	}
	if q.createVAPIDKeysStmt, err = db.PrepareContext(ctx, createVAPIDKeys); err != nil {
		return nil, fmt.Errorf("error preparing query CreateVAPIDKeys: %w", err)
	}
	if q.deleteMonitorStmt, err = db.PrepareContext(ctx, deleteMonitor); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMonitor: %w", err)
	}
	if q.deletePushSubscriptionStmt, err = db.PrepareContext(ctx, deletePushSubscription); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePushSubscription: %w", err)
	}
	if q.deletePushSubscriptionByEndpointStmt, err = db.PrepareContext(ctx, deletePushSubscriptionByEndpoint); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePushSubscriptionByEndpoint: %w", err)
	}
	if q.getChecksStmt, err = db.PrepareContext(ctx, getChecks); err != nil {
		return nil, fmt.Errorf("error preparing query GetChecks: %w", err)
	}
	if q.getMonitorStmt, err = db.PrepareContext(ctx, getMonitor); err != nil {
		return nil, fmt.Errorf("error preparing query GetMonitor: %w", err)
	}
	if q.getMonitorStatsStmt, err = db.PrepareContext(ctx, getMonitorStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetMonitorStats: %w", err)
	}
	if q.getMonitorsStmt, err = db.PrepareContext(ctx, getMonitors); err != nil {
		return nil, fmt.Errorf("error preparing query GetMonitors: %w", err)
	}
	if q.getPushSubscriptionsByMonitorStmt, err = db.PrepareContext(ctx, getPushSubscriptionsByMonitor); err != nil {
		return nil, fmt.Errorf("error preparing query GetPushSubscriptionsByMonitor: %w", err)
	}
	if q.getResponseTimesForPercentilesStmt, err = db.PrepareContext(ctx, getResponseTimesForPercentiles); err != nil {
		return nil, fmt.Errorf("error preparing query GetResponseTimesForPercentiles: %w", err)
	}
	if q.getStatusDataPointsStmt, err = db.PrepareContext(ctx, getStatusDataPoints); err != nil {
		return nil, fmt.Errorf("error preparing query GetStatusDataPoints: %w", err)
	}
	if q.getTimeSeriesDataPointsStmt, err = db.PrepareContext(ctx, getTimeSeriesDataPoints); err != nil {
		return nil, fmt.Errorf("error preparing query GetTimeSeriesDataPoints: %w", err)
	}
	if q.getVAPIDKeysStmt, err = db.PrepareContext(ctx, getVAPIDKeys); err != nil {
		return nil, fmt.Errorf("error preparing query GetVAPIDKeys: %w", err)
	}
	if q.updateMonitorStmt, err = db.PrepareContext(ctx, updateMonitor); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMonitor: %w", err)
	}
	if q.vAPIDKeysExistStmt, err = db.PrepareContext(ctx, vAPIDKeysExist); err != nil {
		return nil, fmt.Errorf("error preparing query VAPIDKeysExist: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.cleanupChecksStmt != nil {
		if cerr := q.cleanupChecksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanupChecksStmt: %w", cerr)
		}
	}
	if q.createCheckStmt != nil {
		if cerr := q.createCheckStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCheckStmt: %w", cerr)
		}
	}
	if q.createMonitorStmt != nil {
		if cerr := q.createMonitorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMonitorStmt: %w", cerr)
		}
	}
	if q.createPushSubscriptionStmt != nil {
		if cerr := q.createPushSubscriptionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPushSubscriptionStmt: %w", cerr)
		}
	}
	if q.createVAPIDKeysStmt != nil {
		if cerr := q.createVAPIDKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createVAPIDKeysStmt: %w", cerr)
		}
	}
	if q.deleteMonitorStmt != nil {
		if cerr := q.deleteMonitorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMonitorStmt: %w", cerr)
		}
	}
	if q.deletePushSubscriptionStmt != nil {
		if cerr := q.deletePushSubscriptionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePushSubscriptionStmt: %w", cerr)
		}
	}
	if q.deletePushSubscriptionByEndpointStmt != nil {
		if cerr := q.deletePushSubscriptionByEndpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePushSubscriptionByEndpointStmt: %w", cerr)
		}
	}
	if q.getChecksStmt != nil {
		if cerr := q.getChecksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChecksStmt: %w", cerr)
		}
	}
	if q.getMonitorStmt != nil {
		if cerr := q.getMonitorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMonitorStmt: %w", cerr)
		}
	}
	if q.getMonitorStatsStmt != nil {
		if cerr := q.getMonitorStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMonitorStatsStmt: %w", cerr)
		}
	}
	if q.getMonitorsStmt != nil {
		if cerr := q.getMonitorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMonitorsStmt: %w", cerr)
		}
	}
	if q.getPushSubscriptionsByMonitorStmt != nil {
		if cerr := q.getPushSubscriptionsByMonitorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPushSubscriptionsByMonitorStmt: %w", cerr)
		}
	}
	if q.getResponseTimesForPercentilesStmt != nil {
		if cerr := q.getResponseTimesForPercentilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getResponseTimesForPercentilesStmt: %w", cerr)
		}
	}
	if q.getStatusDataPointsStmt != nil {
		if cerr := q.getStatusDataPointsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStatusDataPointsStmt: %w", cerr)
		}
	}
	if q.getTimeSeriesDataPointsStmt != nil {
		if cerr := q.getTimeSeriesDataPointsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTimeSeriesDataPointsStmt: %w", cerr)
		}
	}
	if q.getVAPIDKeysStmt != nil {
		if cerr := q.getVAPIDKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVAPIDKeysStmt: %w", cerr)
		}
	}
	if q.updateMonitorStmt != nil {
		if cerr := q.updateMonitorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMonitorStmt: %w", cerr)
		}
	}
	if q.vAPIDKeysExistStmt != nil {
		if cerr := q.vAPIDKeysExistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing vAPIDKeysExistStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                   DBTX
	tx                                   *sql.Tx
	cleanupChecksStmt                    *sql.Stmt
	createCheckStmt                      *sql.Stmt
	createMonitorStmt                    *sql.Stmt
	createPushSubscriptionStmt           *sql.Stmt
	createVAPIDKeysStmt                  *sql.Stmt
	deleteMonitorStmt                    *sql.Stmt
	deletePushSubscriptionStmt           *sql.Stmt
	deletePushSubscriptionByEndpointStmt *sql.Stmt
	getChecksStmt                        *sql.Stmt
	getMonitorStmt                       *sql.Stmt
	getMonitorStatsStmt                  *sql.Stmt
	getMonitorsStmt                      *sql.Stmt
	getPushSubscriptionsByMonitorStmt    *sql.Stmt
	getResponseTimesForPercentilesStmt   *sql.Stmt
	getStatusDataPointsStmt              *sql.Stmt
	getTimeSeriesDataPointsStmt          *sql.Stmt
	getVAPIDKeysStmt                     *sql.Stmt
	updateMonitorStmt                    *sql.Stmt
	vAPIDKeysExistStmt                   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                   tx,
		tx:                                   tx,
		cleanupChecksStmt:                    q.cleanupChecksStmt,
		createCheckStmt:                      q.createCheckStmt,
		createMonitorStmt:                    q.createMonitorStmt,
		createPushSubscriptionStmt:           q.createPushSubscriptionStmt,
		createVAPIDKeysStmt:                  q.createVAPIDKeysStmt,
		deleteMonitorStmt:                    q.deleteMonitorStmt,
		deletePushSubscriptionStmt:           q.deletePushSubscriptionStmt,
		deletePushSubscriptionByEndpointStmt: q.deletePushSubscriptionByEndpointStmt,
		getChecksStmt:                        q.getChecksStmt,
		getMonitorStmt:                       q.getMonitorStmt,
		getMonitorStatsStmt:                  q.getMonitorStatsStmt,
		getMonitorsStmt:                      q.getMonitorsStmt,
		getPushSubscriptionsByMonitorStmt:    q.getPushSubscriptionsByMonitorStmt,
		getResponseTimesForPercentilesStmt:   q.getResponseTimesForPercentilesStmt,
		getStatusDataPointsStmt:              q.getStatusDataPointsStmt,
		getTimeSeriesDataPointsStmt:          q.getTimeSeriesDataPointsStmt,
		getVAPIDKeysStmt:                     q.getVAPIDKeysStmt,
		updateMonitorStmt:                    q.updateMonitorStmt,
		vAPIDKeysExistStmt:                   q.vAPIDKeysExistStmt,
	}
}
