// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.cleanupChecksStmt, err = db.PrepareContext(ctx, cleanupChecks); err != nil {
		return nil, fmt.Errorf("error preparing query CleanupChecks: %w", err)
	}
	if q.createCheckStmt, err = db.PrepareContext(ctx, createCheck); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCheck: %w", err)
	}
	if q.createIncidentStmt, err = db.PrepareContext(ctx, createIncident); err != nil {
		return nil, fmt.Errorf("error preparing query CreateIncident: %w", err)
	}
	if q.createMonitorStmt, err = db.PrepareContext(ctx, createMonitor); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMonitor: %w", err)
	}
	if q.deleteIncidentStmt, err = db.PrepareContext(ctx, deleteIncident); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteIncident: %w", err)
	}
	if q.deleteMonitorStmt, err = db.PrepareContext(ctx, deleteMonitor); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMonitor: %w", err)
	}
	if q.getCheckStmt, err = db.PrepareContext(ctx, getCheck); err != nil {
		return nil, fmt.Errorf("error preparing query GetCheck: %w", err)
	}
	if q.getCheckStatsStmt, err = db.PrepareContext(ctx, getCheckStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetCheckStats: %w", err)
	}
	if q.getChecksStmt, err = db.PrepareContext(ctx, getChecks); err != nil {
		return nil, fmt.Errorf("error preparing query GetChecks: %w", err)
	}
	if q.getIncidentStmt, err = db.PrepareContext(ctx, getIncident); err != nil {
		return nil, fmt.Errorf("error preparing query GetIncident: %w", err)
	}
	if q.getIncidentsStmt, err = db.PrepareContext(ctx, getIncidents); err != nil {
		return nil, fmt.Errorf("error preparing query GetIncidents: %w", err)
	}
	if q.getMonitorStmt, err = db.PrepareContext(ctx, getMonitor); err != nil {
		return nil, fmt.Errorf("error preparing query GetMonitor: %w", err)
	}
	if q.getMonitorIncidentsStmt, err = db.PrepareContext(ctx, getMonitorIncidents); err != nil {
		return nil, fmt.Errorf("error preparing query GetMonitorIncidents: %w", err)
	}
	if q.getMonitorStatusStmt, err = db.PrepareContext(ctx, getMonitorStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetMonitorStatus: %w", err)
	}
	if q.getMonitorsStmt, err = db.PrepareContext(ctx, getMonitors); err != nil {
		return nil, fmt.Errorf("error preparing query GetMonitors: %w", err)
	}
	if q.getUptimeStatsStmt, err = db.PrepareContext(ctx, getUptimeStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetUptimeStats: %w", err)
	}
	if q.resolveIncidentStmt, err = db.PrepareContext(ctx, resolveIncident); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveIncident: %w", err)
	}
	if q.updateIncidentStmt, err = db.PrepareContext(ctx, updateIncident); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateIncident: %w", err)
	}
	if q.updateMonitorStmt, err = db.PrepareContext(ctx, updateMonitor); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMonitor: %w", err)
	}
	if q.upsertCheckStatsStmt, err = db.PrepareContext(ctx, upsertCheckStats); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertCheckStats: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.cleanupChecksStmt != nil {
		if cerr := q.cleanupChecksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanupChecksStmt: %w", cerr)
		}
	}
	if q.createCheckStmt != nil {
		if cerr := q.createCheckStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCheckStmt: %w", cerr)
		}
	}
	if q.createIncidentStmt != nil {
		if cerr := q.createIncidentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createIncidentStmt: %w", cerr)
		}
	}
	if q.createMonitorStmt != nil {
		if cerr := q.createMonitorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMonitorStmt: %w", cerr)
		}
	}
	if q.deleteIncidentStmt != nil {
		if cerr := q.deleteIncidentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteIncidentStmt: %w", cerr)
		}
	}
	if q.deleteMonitorStmt != nil {
		if cerr := q.deleteMonitorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMonitorStmt: %w", cerr)
		}
	}
	if q.getCheckStmt != nil {
		if cerr := q.getCheckStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCheckStmt: %w", cerr)
		}
	}
	if q.getCheckStatsStmt != nil {
		if cerr := q.getCheckStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCheckStatsStmt: %w", cerr)
		}
	}
	if q.getChecksStmt != nil {
		if cerr := q.getChecksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChecksStmt: %w", cerr)
		}
	}
	if q.getIncidentStmt != nil {
		if cerr := q.getIncidentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIncidentStmt: %w", cerr)
		}
	}
	if q.getIncidentsStmt != nil {
		if cerr := q.getIncidentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIncidentsStmt: %w", cerr)
		}
	}
	if q.getMonitorStmt != nil {
		if cerr := q.getMonitorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMonitorStmt: %w", cerr)
		}
	}
	if q.getMonitorIncidentsStmt != nil {
		if cerr := q.getMonitorIncidentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMonitorIncidentsStmt: %w", cerr)
		}
	}
	if q.getMonitorStatusStmt != nil {
		if cerr := q.getMonitorStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMonitorStatusStmt: %w", cerr)
		}
	}
	if q.getMonitorsStmt != nil {
		if cerr := q.getMonitorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMonitorsStmt: %w", cerr)
		}
	}
	if q.getUptimeStatsStmt != nil {
		if cerr := q.getUptimeStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUptimeStatsStmt: %w", cerr)
		}
	}
	if q.resolveIncidentStmt != nil {
		if cerr := q.resolveIncidentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveIncidentStmt: %w", cerr)
		}
	}
	if q.updateIncidentStmt != nil {
		if cerr := q.updateIncidentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateIncidentStmt: %w", cerr)
		}
	}
	if q.updateMonitorStmt != nil {
		if cerr := q.updateMonitorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMonitorStmt: %w", cerr)
		}
	}
	if q.upsertCheckStatsStmt != nil {
		if cerr := q.upsertCheckStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertCheckStatsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                      DBTX
	tx                      *sql.Tx
	cleanupChecksStmt       *sql.Stmt
	createCheckStmt         *sql.Stmt
	createIncidentStmt      *sql.Stmt
	createMonitorStmt       *sql.Stmt
	deleteIncidentStmt      *sql.Stmt
	deleteMonitorStmt       *sql.Stmt
	getCheckStmt            *sql.Stmt
	getCheckStatsStmt       *sql.Stmt
	getChecksStmt           *sql.Stmt
	getIncidentStmt         *sql.Stmt
	getIncidentsStmt        *sql.Stmt
	getMonitorStmt          *sql.Stmt
	getMonitorIncidentsStmt *sql.Stmt
	getMonitorStatusStmt    *sql.Stmt
	getMonitorsStmt         *sql.Stmt
	getUptimeStatsStmt      *sql.Stmt
	resolveIncidentStmt     *sql.Stmt
	updateIncidentStmt      *sql.Stmt
	updateMonitorStmt       *sql.Stmt
	upsertCheckStatsStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                      tx,
		tx:                      tx,
		cleanupChecksStmt:       q.cleanupChecksStmt,
		createCheckStmt:         q.createCheckStmt,
		createIncidentStmt:      q.createIncidentStmt,
		createMonitorStmt:       q.createMonitorStmt,
		deleteIncidentStmt:      q.deleteIncidentStmt,
		deleteMonitorStmt:       q.deleteMonitorStmt,
		getCheckStmt:            q.getCheckStmt,
		getCheckStatsStmt:       q.getCheckStatsStmt,
		getChecksStmt:           q.getChecksStmt,
		getIncidentStmt:         q.getIncidentStmt,
		getIncidentsStmt:        q.getIncidentsStmt,
		getMonitorStmt:          q.getMonitorStmt,
		getMonitorIncidentsStmt: q.getMonitorIncidentsStmt,
		getMonitorStatusStmt:    q.getMonitorStatusStmt,
		getMonitorsStmt:         q.getMonitorsStmt,
		getUptimeStatsStmt:      q.getUptimeStatsStmt,
		resolveIncidentStmt:     q.resolveIncidentStmt,
		updateIncidentStmt:      q.updateIncidentStmt,
		updateMonitorStmt:       q.updateMonitorStmt,
		upsertCheckStatsStmt:    q.upsertCheckStatsStmt,
	}
}
