// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Check struct {
	ID           int64     `json:"id"`
	MonitorID    int64     `json:"monitorId"`
	StatusCode   *int64    `json:"statusCode"`
	ResponseTime *int64    `json:"responseTime"`
	Error        *string   `json:"error"`
	IsUp         bool      `json:"isUp"`
	CheckedAt    time.Time `json:"checkedAt"`
}

type CheckStat struct {
	ID               int64     `json:"id"`
	MonitorID        int64     `json:"monitorId"`
	HourTimestamp    time.Time `json:"hourTimestamp"`
	TotalChecks      int64     `json:"totalChecks"`
	SuccessfulChecks int64     `json:"successfulChecks"`
	AvgResponseTime  *int64    `json:"avgResponseTime"`
	CreatedAt        time.Time `json:"createdAt"`
}

type Incident struct {
	ID         int64      `json:"id"`
	MonitorID  int64      `json:"monitorId"`
	Reason     *string    `json:"reason"`
	ResolvedAt *time.Time `json:"resolvedAt"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type Monitor struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Url           string    `json:"url"`
	CheckInterval int64     `json:"checkInterval"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}
