// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Check struct {
	MonitorID    int64   `json:"monitorId"`
	StatusCode   int64   `json:"statusCode"`
	ResponseTime int64   `json:"responseTime"`
	Error        *string `json:"error"`
	IsUp         bool    `json:"isUp"`
	CheckedAt    int64   `json:"checkedAt"`
}

type Monitor struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Url           string `json:"url"`
	CheckInterval int64  `json:"checkInterval"`
	CreatedAt     int64  `json:"createdAt"`
}

type PushSubscription struct {
	ID        int64  `json:"id"`
	MonitorID int64  `json:"monitorId"`
	Endpoint  string `json:"endpoint"`
	P256dhKey string `json:"p256dhKey"`
	AuthKey   string `json:"authKey"`
	CreatedAt int64  `json:"createdAt"`
}

type VapidKey struct {
	ID         int64  `json:"id"`
	PublicKey  string `json:"publicKey"`
	PrivateKey string `json:"privateKey"`
	CreatedAt  int64  `json:"createdAt"`
}
