// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package db

import (
	"context"
	"time"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO
  monitors (name, url, check_interval, is_active)
VALUES
  (?, ?, ?, ?) RETURNING id, name, url, check_interval, is_active, created_at, updated_at
`

type CreateMonitorParams struct {
	Name          string `json:"name"`
	Url           string `json:"url"`
	CheckInterval int64  `json:"checkInterval"`
	IsActive      bool   `json:"isActive"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg *CreateMonitorParams) (*Monitor, error) {
	row := q.queryRow(ctx, q.createMonitorStmt, createMonitor,
		arg.Name,
		arg.Url,
		arg.CheckInterval,
		arg.IsActive,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CheckInterval,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors
WHERE
  id = ?
`

func (q *Queries) DeleteMonitor(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteMonitorStmt, deleteMonitor, id)
	return err
}

const getMonitor = `-- name: GetMonitor :one
SELECT
  id, name, url, check_interval, is_active, created_at, updated_at
FROM
  monitors
WHERE
  id = ?
`

func (q *Queries) GetMonitor(ctx context.Context, id int64) (*Monitor, error) {
	row := q.queryRow(ctx, q.getMonitorStmt, getMonitor, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CheckInterval,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMonitorStatus = `-- name: GetMonitorStatus :one
SELECT
  m.id, m.name, m.url, m.check_interval, m.is_active, m.created_at, m.updated_at,
  c.is_up,
  c.checked_at,
  c.response_time
FROM
  monitors m
  LEFT JOIN checks c ON c.id = (
    SELECT
      id
    FROM
      checks
    WHERE
      monitor_id = m.id
    ORDER BY
      checked_at DESC
    LIMIT
      1
  )
WHERE
  m.id = ?
`

type GetMonitorStatusRow struct {
	ID            int64      `json:"id"`
	Name          string     `json:"name"`
	Url           string     `json:"url"`
	CheckInterval int64      `json:"checkInterval"`
	IsActive      bool       `json:"isActive"`
	CreatedAt     time.Time  `json:"createdAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
	IsUp          *bool      `json:"isUp"`
	CheckedAt     *time.Time `json:"checkedAt"`
	ResponseTime  *int64     `json:"responseTime"`
}

func (q *Queries) GetMonitorStatus(ctx context.Context, id int64) (*GetMonitorStatusRow, error) {
	row := q.queryRow(ctx, q.getMonitorStatusStmt, getMonitorStatus, id)
	var i GetMonitorStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CheckInterval,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsUp,
		&i.CheckedAt,
		&i.ResponseTime,
	)
	return &i, err
}

const getMonitors = `-- name: GetMonitors :many
SELECT
  id, name, url, check_interval, is_active, created_at, updated_at
FROM
  monitors
WHERE
  is_active = 1
`

func (q *Queries) GetMonitors(ctx context.Context) ([]*Monitor, error) {
	rows, err := q.query(ctx, q.getMonitorsStmt, getMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.CheckInterval,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUptimeStats = `-- name: GetUptimeStats :one
SELECT
  COUNT(*) as total_checks,
  SUM(
    CASE
      WHEN is_up THEN 1
      ELSE 0
    END
  ) as successful_checks,
  AVG(response_time) as avg_response_time
FROM
  checks
WHERE
  monitor_id = ?
  AND checked_at > datetime ('now', '-24 hours')
`

type GetUptimeStatsRow struct {
	TotalChecks      int64    `json:"totalChecks"`
	SuccessfulChecks *float64 `json:"successfulChecks"`
	AvgResponseTime  *float64 `json:"avgResponseTime"`
}

func (q *Queries) GetUptimeStats(ctx context.Context, monitorID int64) (*GetUptimeStatsRow, error) {
	row := q.queryRow(ctx, q.getUptimeStatsStmt, getUptimeStats, monitorID)
	var i GetUptimeStatsRow
	err := row.Scan(&i.TotalChecks, &i.SuccessfulChecks, &i.AvgResponseTime)
	return &i, err
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET
  name = COALESCE(?, name),
  url = COALESCE(?, url),
  check_interval = COALESCE(?, check_interval),
  is_active = COALESCE(?, is_active)
WHERE
  id = ? RETURNING id, name, url, check_interval, is_active, created_at, updated_at
`

type UpdateMonitorParams struct {
	Name          string `json:"name"`
	Url           string `json:"url"`
	CheckInterval int64  `json:"checkInterval"`
	IsActive      bool   `json:"isActive"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg *UpdateMonitorParams) (*Monitor, error) {
	row := q.queryRow(ctx, q.updateMonitorStmt, updateMonitor,
		arg.Name,
		arg.Url,
		arg.CheckInterval,
		arg.IsActive,
		arg.ID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CheckInterval,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
