// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package db

import (
	"context"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO
  monitors (name, url, check_interval)
VALUES
  (?, ?, ?) RETURNING id, name, url, check_interval, created_at, updated_at
`

type CreateMonitorParams struct {
	Name          string `json:"name"`
	Url           string `json:"url"`
	CheckInterval int64  `json:"checkInterval"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg *CreateMonitorParams) (*Monitor, error) {
	row := q.queryRow(ctx, q.createMonitorStmt, createMonitor, arg.Name, arg.Url, arg.CheckInterval)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CheckInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors
WHERE
  id = ?
`

func (q *Queries) DeleteMonitor(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteMonitorStmt, deleteMonitor, id)
	return err
}

const getMonitor = `-- name: GetMonitor :one
SELECT
  id, name, url, check_interval, created_at, updated_at
FROM
  monitors
WHERE
  id = ?
`

func (q *Queries) GetMonitor(ctx context.Context, id int64) (*Monitor, error) {
	row := q.queryRow(ctx, q.getMonitorStmt, getMonitor, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CheckInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMonitors = `-- name: GetMonitors :many
SELECT
  id, name, url, check_interval, created_at, updated_at
FROM
  monitors
`

func (q *Queries) GetMonitors(ctx context.Context) ([]*Monitor, error) {
	rows, err := q.query(ctx, q.getMonitorsStmt, getMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.CheckInterval,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET
  name = COALESCE(?, name),
  url = COALESCE(?, url),
  check_interval = COALESCE(?, check_interval)
WHERE
  id = ? RETURNING id, name, url, check_interval, created_at, updated_at
`

type UpdateMonitorParams struct {
	Name          string `json:"name"`
	Url           string `json:"url"`
	CheckInterval int64  `json:"checkInterval"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg *UpdateMonitorParams) (*Monitor, error) {
	row := q.queryRow(ctx, q.updateMonitorStmt, updateMonitor,
		arg.Name,
		arg.Url,
		arg.CheckInterval,
		arg.ID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CheckInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
