// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"
)

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors
WHERE
  id = ?
`

func (q *Queries) DeleteMonitor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMonitor, id)
	return err
}

const getMonitors = `-- name: GetMonitors :many
SELECT
  id, name, url, type, group_name, check_interval, retries, degraded_threshold, expected_status, keyword, ignore_cert_expiry, created_at
FROM
  monitors
ORDER BY
  id
`

func (q *Queries) GetMonitors(ctx context.Context) ([]*Monitor, error) {
	rows, err := q.db.QueryContext(ctx, getMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Type,
			&i.GroupName,
			&i.CheckInterval,
			&i.Retries,
			&i.DegradedThreshold,
			&i.ExpectedStatus,
			&i.Keyword,
			&i.IgnoreCertExpiry,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMonitor = `-- name: UpsertMonitor :one
INSERT INTO
  monitors (
    name,
    url,
    type,
    group_name,
    check_interval,
    retries,
    degraded_threshold,
    expected_status,
    keyword,
    ignore_cert_expiry
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE
SET
  url = excluded.url,
  type = excluded.type,
  group_name = excluded.group_name,
  check_interval = excluded.check_interval,
  retries = excluded.retries,
  degraded_threshold = excluded.degraded_threshold,
  expected_status = excluded.expected_status,
  keyword = excluded.keyword,
  ignore_cert_expiry = excluded.ignore_cert_expiry RETURNING id, name, url, type, group_name, check_interval, retries, degraded_threshold, expected_status, keyword, ignore_cert_expiry, created_at
`

type UpsertMonitorParams struct {
	Name              string `json:"name"`
	Url               string `json:"url"`
	Type              string `json:"type"`
	GroupName         string `json:"groupName"`
	CheckInterval     int64  `json:"checkInterval"`
	Retries           int64  `json:"retries"`
	DegradedThreshold int64  `json:"degradedThreshold"`
	ExpectedStatus    int64  `json:"expectedStatus"`
	Keyword           string `json:"keyword"`
	IgnoreCertExpiry  bool   `json:"ignoreCertExpiry"`
}

func (q *Queries) UpsertMonitor(ctx context.Context, arg *UpsertMonitorParams) (*Monitor, error) {
	row := q.db.QueryRowContext(ctx, upsertMonitor,
		arg.Name,
		arg.Url,
		arg.Type,
		arg.GroupName,
		arg.CheckInterval,
		arg.Retries,
		arg.DegradedThreshold,
		arg.ExpectedStatus,
		arg.Keyword,
		arg.IgnoreCertExpiry,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.GroupName,
		&i.CheckInterval,
		&i.Retries,
		&i.DegradedThreshold,
		&i.ExpectedStatus,
		&i.Keyword,
		&i.IgnoreCertExpiry,
		&i.CreatedAt,
	)
	return &i, err
}
