// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notify.sql

package db

import (
	"context"
)

const createPushSubscription = `-- name: CreatePushSubscription :exec
INSERT INTO
  push_subscriptions (monitor_id, endpoint, p256dh_key, auth_key)
VALUES
  (?, ?, ?, ?)
`

type CreatePushSubscriptionParams struct {
	MonitorID int64  `json:"monitorId"`
	Endpoint  string `json:"endpoint"`
	P256dhKey string `json:"p256dhKey"`
	AuthKey   string `json:"authKey"`
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg *CreatePushSubscriptionParams) error {
	_, err := q.exec(ctx, q.createPushSubscriptionStmt, createPushSubscription,
		arg.MonitorID,
		arg.Endpoint,
		arg.P256dhKey,
		arg.AuthKey,
	)
	return err
}

const createVAPIDKeys = `-- name: CreateVAPIDKeys :exec
INSERT INTO
  vapid_keys (id, public_key, private_key)
VALUES
  (1, ?, ?)
`

type CreateVAPIDKeysParams struct {
	PublicKey  string `json:"publicKey"`
	PrivateKey string `json:"privateKey"`
}

func (q *Queries) CreateVAPIDKeys(ctx context.Context, arg *CreateVAPIDKeysParams) error {
	_, err := q.exec(ctx, q.createVAPIDKeysStmt, createVAPIDKeys, arg.PublicKey, arg.PrivateKey)
	return err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions
WHERE
  endpoint = ?
  AND monitor_id = ?
`

type DeletePushSubscriptionParams struct {
	Endpoint  string `json:"endpoint"`
	MonitorID int64  `json:"monitorId"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg *DeletePushSubscriptionParams) error {
	_, err := q.exec(ctx, q.deletePushSubscriptionStmt, deletePushSubscription, arg.Endpoint, arg.MonitorID)
	return err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions
WHERE
  endpoint = ?
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.exec(ctx, q.deletePushSubscriptionByEndpointStmt, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const getPushSubscriptionsByMonitor = `-- name: GetPushSubscriptionsByMonitor :many
SELECT
  id,
  monitor_id,
  endpoint,
  p256dh_key,
  auth_key,
  created_at
FROM
  push_subscriptions
WHERE
  monitor_id = ?
`

func (q *Queries) GetPushSubscriptionsByMonitor(ctx context.Context, monitorID int64) ([]*PushSubscription, error) {
	rows, err := q.query(ctx, q.getPushSubscriptionsByMonitorStmt, getPushSubscriptionsByMonitor, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.Endpoint,
			&i.P256dhKey,
			&i.AuthKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVAPIDKeys = `-- name: GetVAPIDKeys :one
SELECT
  id,
  public_key,
  private_key,
  created_at
FROM
  vapid_keys
WHERE
  id = 1
`

func (q *Queries) GetVAPIDKeys(ctx context.Context) (*VapidKey, error) {
	row := q.queryRow(ctx, q.getVAPIDKeysStmt, getVAPIDKeys)
	var i VapidKey
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.CreatedAt,
	)
	return &i, err
}

const vAPIDKeysExist = `-- name: VAPIDKeysExist :one
SELECT
  COUNT(*) as count
FROM
  vapid_keys
WHERE
  id = 1
`

func (q *Queries) VAPIDKeysExist(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.vAPIDKeysExistStmt, vAPIDKeysExist)
	var count int64
	err := row.Scan(&count)
	return count, err
}
