// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CleanupChecks(ctx context.Context, days *string) error
	CreateCheck(ctx context.Context, arg *CreateCheckParams) (*Check, error)
	CreateIncident(ctx context.Context, arg *CreateIncidentParams) (*Incident, error)
	CreateMonitor(ctx context.Context, arg *CreateMonitorParams) (*Monitor, error)
	DeleteIncident(ctx context.Context, id int64) error
	DeleteMonitor(ctx context.Context, id int64) error
	GetChecks(ctx context.Context, seconds *string) ([]*Check, error)
	GetIncident(ctx context.Context, id int64) (*Incident, error)
	GetIncidents(ctx context.Context, monitorID int64) ([]*Incident, error)
	GetMonitor(ctx context.Context, id int64) (*Monitor, error)
	GetMonitorIncidents(ctx context.Context, arg *GetMonitorIncidentsParams) ([]*Incident, error)
	GetMonitors(ctx context.Context) ([]*Monitor, error)
	ResolveIncident(ctx context.Context, id int64) (*Incident, error)
	UpdateIncident(ctx context.Context, arg *UpdateIncidentParams) (*Incident, error)
	UpdateMonitor(ctx context.Context, arg *UpdateMonitorParams) (*Monitor, error)
}

var _ Querier = (*Queries)(nil)
