// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CleanupChecks(ctx context.Context, days *string) error
	CreateCheck(ctx context.Context, arg *CreateCheckParams) (*Check, error)
	CreateMonitor(ctx context.Context, arg *CreateMonitorParams) (*Monitor, error)
	CreatePushSubscription(ctx context.Context, arg *CreatePushSubscriptionParams) error
	CreateVAPIDKeys(ctx context.Context, arg *CreateVAPIDKeysParams) error
	DeleteMonitor(ctx context.Context, id int64) error
	DeletePushSubscription(ctx context.Context, arg *DeletePushSubscriptionParams) error
	DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error
	GetChecks(ctx context.Context, seconds *string) ([]*Check, error)
	GetMonitor(ctx context.Context, id int64) (*Monitor, error)
	GetMonitorStats(ctx context.Context, seconds *string) ([]*GetMonitorStatsRow, error)
	GetMonitors(ctx context.Context) ([]*Monitor, error)
	GetPushSubscriptionsByMonitor(ctx context.Context, monitorID int64) ([]*PushSubscription, error)
	GetResponseTimesForPercentiles(ctx context.Context, seconds *string) ([]*GetResponseTimesForPercentilesRow, error)
	GetStatusDataPoints(ctx context.Context, arg *GetStatusDataPointsParams) ([]*GetStatusDataPointsRow, error)
	GetTimeSeriesDataPoints(ctx context.Context, arg *GetTimeSeriesDataPointsParams) ([]*GetTimeSeriesDataPointsRow, error)
	GetVAPIDKeys(ctx context.Context) (*VapidKey, error)
	UpdateMonitor(ctx context.Context, arg *UpdateMonitorParams) (*Monitor, error)
	VAPIDKeysExist(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
