// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
	"time"
)

const getCheckStats = `-- name: GetCheckStats :many
SELECT
  hour_timestamp,
  total_checks,
  successful_checks,
  avg_response_time
FROM
  check_stats
WHERE
  monitor_id = ?
  AND hour_timestamp >= datetime ('now', ?)
ORDER BY
  hour_timestamp ASC
`

type GetCheckStatsParams struct {
	MonitorID int64       `json:"monitorId"`
	Datetime  interface{} `json:"datetime"`
}

type GetCheckStatsRow struct {
	HourTimestamp    time.Time `json:"hourTimestamp"`
	TotalChecks      int64     `json:"totalChecks"`
	SuccessfulChecks int64     `json:"successfulChecks"`
	AvgResponseTime  *int64    `json:"avgResponseTime"`
}

func (q *Queries) GetCheckStats(ctx context.Context, arg *GetCheckStatsParams) ([]*GetCheckStatsRow, error) {
	rows, err := q.query(ctx, q.getCheckStatsStmt, getCheckStats, arg.MonitorID, arg.Datetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCheckStatsRow
	for rows.Next() {
		var i GetCheckStatsRow
		if err := rows.Scan(
			&i.HourTimestamp,
			&i.TotalChecks,
			&i.SuccessfulChecks,
			&i.AvgResponseTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCheckStats = `-- name: UpsertCheckStats :exec
INSERT INTO
  check_stats (
    monitor_id,
    hour_timestamp,
    total_checks,
    successful_checks,
    avg_response_time
  )
VALUES
  (?, ?, ?, ?, ?) ON CONFLICT (monitor_id, hour_timestamp) DO
UPDATE
SET
  total_checks = total_checks + excluded.total_checks,
  successful_checks = successful_checks + excluded.successful_checks,
  avg_response_time = (avg_response_time + excluded.avg_response_time) / 2
`

type UpsertCheckStatsParams struct {
	MonitorID        int64     `json:"monitorId"`
	HourTimestamp    time.Time `json:"hourTimestamp"`
	TotalChecks      int64     `json:"totalChecks"`
	SuccessfulChecks int64     `json:"successfulChecks"`
	AvgResponseTime  *int64    `json:"avgResponseTime"`
}

func (q *Queries) UpsertCheckStats(ctx context.Context, arg *UpsertCheckStatsParams) error {
	_, err := q.exec(ctx, q.upsertCheckStatsStmt, upsertCheckStats,
		arg.MonitorID,
		arg.HourTimestamp,
		arg.TotalChecks,
		arg.SuccessfulChecks,
		arg.AvgResponseTime,
	)
	return err
}
